# Sharelatex Base Image (sharelatex/sharelatex-base)

FROM phusion/baseimage:0.9.16

ENV baseDir .

ENV DEBIAN_FRONTEND noninteractive
# apt-get update is run by setup_6.x
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo bash - \
  && apt-get install -y \
     build-essential \
     wget \
     nodejs \
     unzip \
     time \
     imagemagick \
     optipng \
     strace \
     nginx \
     git \
     python \
     zlib1g-dev \
     libpcre3-dev \
     aspell \
     '^aspell-.*' \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN wget -O /tmp/qpdf-6.0.0.tar.gz https://s3.amazonaws.com/sharelatex-random-files/qpdf-6.0.0.tar.gz \
  && tar -C /tmp -xzf /tmp/qpdf-6.0.0.tar.gz \
  && cd /tmp/qpdf-6.0.0 \
  && ./configure \
  && make \
  && make install \
  && ldconfig \
  && rm -rf /tmp/qpdf-6.0.0 /tmp/qpdf-6.0.0.tar.gz

# Install TexLive
RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz \
  && mkdir /install-tl-unx \
  && tar -xvf install-tl-unx.tar.gz -C /install-tl-unx --strip-components=1 \
  &&  echo "selected_scheme scheme-basic" >> /install-tl-unx/texlive.profile \
  && /install-tl-unx/install-tl -profile /install-tl-unx/texlive.profile \
  && rm -rf /install-tl-unx install-tl-unx.tar.gz

ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2018/bin/x86_64-linux/
RUN tlmgr install latexmk texcount

RUN npm install -g grunt-cli

# Set up sharelatex user and home directory
RUN adduser --system --group --home /var/www/sharelatex --no-create-home sharelatex; \
	mkdir -p /var/lib/sharelatex; \
	chown www-data:www-data /var/lib/sharelatex; \
	mkdir -p /var/log/sharelatex; \
	chown www-data:www-data /var/log/sharelatex; \
	mkdir -p /var/lib/sharelatex/data/template_files; \
	chown www-data:www-data /var/lib/sharelatex/data/template_files;

